# 动态规划

### 动态规划可以帮助你在给定约束条件下找到最优解
### 在问题可以分成彼此独立的且离散的子问题时，可用动态规划
### 动态规划都涉及网格，格内记录需要优化的值

In [34]:
import numpy as np
def longest_common_substring(word1,word2):
    col_num = len(word1)
    row_num = len(word2)
    col_word = [x for x in word1 if x.isalpha()]
    row_word = [x for x in word2 if x.isalpha()]
    
    print(col_word)
    print(row_word)

    grid = np.zeros((row_num+1,col_num+1))
    g_max = 0
    
    for i in range(row_num):
        for j in range(col_num):
            if row_word[i] == col_word[j]:
                grid[i+1][j+1] = grid[i][j] + 1
                if grid[i+1][j+1] > g_max:
                    g_max = grid[i+1][j+1]
    print(grid)
    return g_max

In [35]:
longest_common_substring('hahaha','qinhaha')

['h', 'a', 'h', 'a', 'h', 'a']
['q', 'i', 'n', 'h', 'a', 'h', 'a']
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  2.  0.  2.  0.  2.]
 [ 0.  1.  0.  3.  0.  3.  0.]
 [ 0.  0.  2.  0.  4.  0.  4.]]


4.0

In [130]:
def longest_common_sequence(w1,w2):
    v = [[0 for x in range(len(w1)+1)]for y in range(len(w2)+1)]
    d = [[None for x in range(len(w1)+1)]for y in range(len(w2)+1)]
        
    for i in range(len(w2)):
        for j in range(len(w1)):
            if w2[i] == w1[j]:
                v[i+1][j+1] = v[i][j]+1
                d[i+1][j+1] = 'ok'
            elif v[i+1][j] > v[i][j+1]:
                v[i+1][j+1] = v[i+1][j]
                d[i+1][j+1] = 'left'
            else:
                v[i+1][j+1] = v[i][j+1]
                d[i+1][j+1] = 'up'
       
    p1 = len(w2)
    p2 = len(w1)
    l = []
    while v[p1][p2]:
        c = d[p1][p2]
        if c == 'ok':
            l.append(w2[p1-1])
            p1 -= 1
            p2 -= 1
        elif c == 'left':
            p2 -= 1
        elif c == 'up':
            p1 -= 1
    l = l[::-1] 
    return ''.join(l)

In [131]:
longest_common_sequence('haha','qinhaha')

'haha'